### PR TITLE
Filtered Records, additional changes

### PR DESCRIPTION
**Pull request by JesseSprinkle**
In this PR, I changed the routing, permissions of several things, naming of some stuff. Just changes.

### CODE REVIEW

**Comment by rhollier** [comment]
Hey, Jesse are these the changes that we talked about in the scrum meetings, with "users" being changed to "senators", and all that?

**Comment by rhollier** [comment]
Hey Jesse, I just ran pulled from your branch.  I ran rubocop, it had zero failures. Good Job! I ran rspec. It had zero failures. Good Job!. And I also ran it on the local host, and there are no errors. Everything is running smoothly. I also checked the changed files. I did not find any bugs. 

To me, It looks fine to merge!

**Review by magnipopam — APPROVED** [review]
I went through all the pages, and everything seems to be working as it should. I think it is good to merge.

**Comment by JesseSprinkle** [comment]
> Hey, Jesse are these the changes that we talked about in the scrum meetings, with "users" being changed to "senators", and all that?

Yes, just thought it made more sense to have the users name Senators

**Pull request merged**
